<?php

namespace AppBundle\Repository;

/**
 * autorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class autorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName ($limit = null)
    {
        $search = $this->createQueryBuilder('autor')
            ->select('autor')
            ->addOrderBy('autor.lastLogDate', 'DESC');

        if (false === is_null($limit))
            $search->setMaxResults($limit);

        return $search->getQuery()
            ->getResult();
    }
}
