<?php

namespace AppBundle\Repository;

/**
 * postRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class postRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByID ($id, $limit = null)
    {
        $search = $this->createQueryBuilder('post')
            ->select('post')
            ->where('post.autor_id = ?1')
            ->addOrderBy('post.date', 'DESC')
            ->setParameter(1 , $id);

        if (false === is_null($limit))
            $search->setMaxResults($limit);

        return $search->getQuery()
            ->getResult();
    }
}
