AppBundle\Entity\autor:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\autorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        lastLogDate:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    oneToMany:
        post:
            targetEntity: post
            mappedBy: autor
        comment:
            targetEntity: comment
            mappedBy: autor