AppBundle\Entity\tag:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\tagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToMany:
        post:
            targetEntity: post
            mappedBy: tag